## 1. Importing and inspecting the dataset

In [22]:
import pandas as pd
import numpy as np
df = pd.read_csv('Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [25]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [26]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## 2. Identifying data quality issues.

In [27]:
# Check missing values
missing = df.isnull().sum()
missing_summary = pd.DataFrame({'Missing Count': missing})
missing_summary[missing_summary['Missing Count'] > 0]

          Missing Count
Age                 177
Cabin               687
Embarked              2

In [ ]:
# Check for duplicate rows
duplicate = df.duplicated().sum()
print(f"There are {duplicate} duplicate rows in the dataset.")

There are 0 duplicate rows in the dataset.

In [ ]:
# Check unique values in categorical columns
print("Sex:", df['Sex'].unique())
print("Embarked:", df['Embarked'].unique())
print("Pclass:", df['Pclass'].unique())
print("Survived:", df['Survived'].unique())

Sex: <StringArray>
['male', 'female']
Length: 2, dtype: str
Embarked: <StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str
Pclass: [3 1 2]
Survived: [0 1]

## 3. Handling missing values using appropriate techniques.

In [ ]:
# Fill missing values in 'Age' column with median because it is a continuous variable and median is less affected by outliers than mean.
df['Age'] = df['Age'].fillna(df['Age'].median())

In [ ]:
# Fill missing values in 'Embarked' column with mode because it is a categorical variable and mode is the most frequent value.
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
# Fill missing values in 'Cabin' column with 'Unknown' because it is a categorical variable and we want to keep track of missing values.
df['Cabin'] = df['Cabin'].fillna('Unknown')

In [ ]:
# Check for missing values after filling
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## 4.Detecting and removing duplicate records

In [34]:
print(f"Duplicate rows found: {duplicate}")

if duplicate > 0:
    df = df.drop_duplicates()
    print("Duplicates removed.")
else:
    print("No duplicate rows to remove.")

Duplicate rows found: 0
No duplicate rows to remove.

## 5. Changing data types of columns to appropriate types.

In [35]:
df['Survived'] = df['Survived'].astype('category')
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

df.dtypes

PassengerId       int64
Survived       category
Pclass         category
Name                str
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket              str
Fare            float64
Cabin               str
Embarked       category
dtype: object

## 6. Renaming columns where necessary to improve readability.

In [36]:
df = df.rename(columns={
    'SibSp': 'Sibling or Spouses Aboard',
    'Parch': 'Parents or Children Aboard',
    'Pclass': 'Passenger Class',
    'Embarked': 'Embarkation'})
df.columns

Index(['PassengerId', 'Survived', 'Passenger Class', 'Name', 'Sex', 'Age',
       'Sibling or Spouses Aboard', 'Parents or Children Aboard', 'Ticket',
       'Fare', 'Cabin', 'Embarkation'],
      dtype='str')

In [ ]:
print(df.iloc[78])

PassengerId                                              79
Survived                                                  1
Passenger Class                                           2
Name                          Caldwell, Master. Alden Gates
Sex                                                    male
Age                                                    0.83
Sibling or Spouses Aboard                                 0
Parents or Children Aboard                                2
Ticket                                               248738
Fare                                                   29.0
Cabin                                               Unknown
Embarkation                                               S
Name: 78, dtype: object

## 7. Making it more readable

In [38]:
df["Sex"] = df["Sex"].map({"male":"Male", "female":"Female"})
df["Embarkation"] = df["Embarkation"].map({"C":"Cherbourg", "Q":"Queenstown", "S":"Southampton"})
df["Passenger Class"] = df["Passenger Class"].map({1:"First Class", 2:"Second Class", 3:"Third Class"})
df["Survived"] = df["Survived"].map({0:"No", 1:"Yes"})
df.head()

,PassengerId,Survived,Passenger Class,Name,Sex,Age,Sibling or Spouses Aboard,Parents or Children Aboard,Ticket,Fare,Cabin,Embarkation
0,1,No,Third Class,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,Southampton
1,2,Yes,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,Yes,Third Class,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,Southampton
3,4,Yes,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,Southampton
4,5,No,Third Class,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,Southampton

In [39]:
df['Fare'] = df['Fare'].round(2)
df.head()

,PassengerId,Survived,Passenger Class,Name,Sex,Age,Sibling or Spouses Aboard,Parents or Children Aboard,Ticket,Fare,Cabin,Embarkation
0,1,No,Third Class,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.25,Unknown,Southampton
1,2,Yes,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.28,C85,Cherbourg
2,3,Yes,Third Class,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.92,Unknown,Southampton
3,4,Yes,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.10,C123,Southampton
4,5,No,Third Class,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.05,Unknown,Southampton

## 8. Saving the cleaned dataset to a new CSV file for future use.

In [40]:
df.to_csv('cleaned_titanic.csv', index=False)